# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-03 11:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekNumber', models.IntegerField()),
                ('homeScore', models.IntegerField(null=True)),
                ('awayScore', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HumanInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espnID', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('abbr', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='PreviewStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekNumber', models.IntegerField()),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PlayerInstance')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('year', models.IntegerField(default=2016)),
                ('currentWeek', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espnID', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='WeekStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekNumber', models.IntegerField()),
                ('rushingYards', models.IntegerField(default=0)),
                ('rushingAttempts', models.IntegerField(default=0)),
                ('rushingFumbles', models.IntegerField(default=0)),
                ('rushingTDs', models.IntegerField(default=0)),
                ('passingYards', models.IntegerField(default=0)),
                ('passingAttempts', models.IntegerField(default=0)),
                ('passingFumbles', models.IntegerField(default=0)),
                ('passingTDs', models.IntegerField(default=0)),
                ('throwingYards', models.IntegerField(default=0)),
                ('throwingAttempts', models.IntegerField(default=0)),
                ('throwingInterceptions', models.IntegerField(default=0)),
                ('defenseSacks', models.IntegerField(default=0)),
                ('defenseFumbles', models.IntegerField(default=0)),
                ('defenseInterceptions', models.IntegerField(default=0)),
                ('kickerFG', models.IntegerField(default=0)),
                ('kickerPAT', models.IntegerField(default=0)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.PlayerInstance')),
            ],
        ),
        migrations.AddField(
            model_name='playerinstance',
            name='pos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Position'),
        ),
        migrations.AddField(
            model_name='playerinstance',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Team'),
        ),
        migrations.AddField(
            model_name='humaninstance',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Season'),
        ),
        migrations.AddField(
            model_name='humaninstance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Human'),
        ),
        migrations.AddField(
            model_name='gameinstance',
            name='awayTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awayGames', to='core.HumanInstance'),
        ),
        migrations.AddField(
            model_name='gameinstance',
            name='homeTeam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeGames', to='core.HumanInstance'),
        ),
        migrations.AddField(
            model_name='gameinstance',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Season'),
        ),
    ]
